### ISSUE TITLE
Question about time-consistent mesh

### ISSUE THREAD

**Issue by Net-Maker** [jefftan969/dressrecon#2]
Hi Jeff,
    It's an excellent work! I wonder how to get the time-consistent mesh from SDF. I haven't seen it on paper.

**Comment by jefftan969** [comment]
Thank you for your interest. We use marching cubes at 256 resolution to extract a mesh from the canonical SDF shape. We don't change the canonical mesh faces over time and just warp the mesh vertices to each time t using forward warping fields.
